name: Build and check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  pull-requests: write
  contents: read
  checks: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Run tests
        run: ./gradlew test
      - name: Run Ktlint check
        run: ./gradlew ktCh --continue
      - name: Upload test results
        uses: actions/upload-artifact@v3.1.0
        if: always()
        with:
          name: test-results
          path: build/test-results/test/
  test-reporter:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: test-results/test/
      - name: Make test report
        uses: dorny/test-reporter@v1
        with:
          name: Test Report
          path: 'test-results/test/*.xml'
          reporter: java-junit
